# translation of python-meh.master.po to Bengali INDIA
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Runa Bhattacharjee <runab@redhat.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: python-meh.master\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-09-07 23:35+0530\n"
"Last-Translator: Runa Bhattacharjee <runab@redhat.com>\n"
"Language-Team: Bengali INDIA <anubad@lists.ankur.org.in>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "ডাম্প লেখা হয়েছে"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr "ত্রুটির তথ্য বিশিষ্ট ফাইলটি সাফল্যের সাথে ডিস্কে লেখা হয়েছে।  প্রোগ্রাম থেকে বর্তমানে প্রস্থান করা হবে।"

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "ডাম্প লেখা হয়নি"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "ত্রুটির রিপোর্ট লিখতে সমস্যা দেখা দিয়েছে।"

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "নোটওয়ার্ক উপলব্ধ নেই"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr "সক্রিয় নেটওয়ার্ক ডিভাইস উপলব্ধ না থাকার কারণে বাগ রিপোর্ট সংরক্ষণ করতে ব্যর্থ।"

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"bugzilla-র সাথে যোগাযোগকালে নিম্নলিখিত সমস্যার কারণে বাগটি দায়ের করা যায়নি:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"বাগের কিছু ক্ষেত্রে ভুল তথ্য উপস্থিত থাকার ফলে এই বাগটি দায়ের করা সম্ভব হয়নি।  বাগ দায়ের করার প্রোগ্রামের মধ্যে উপস্থিত ত্রুটির ফলে সম্ভবত এই সমস্যা দেখা দিয়েছে:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "বাগ দায়ের করতে ব্যর্থ"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "বাগ দায়ের করার ব্যবস্থা সমর্থিত নয়"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr "আপনার ব্যবহৃত ডিস্ট্রিবিউশন দ্বারা বাগ দায়ের করার কোনো ব্যবস্থা সমর্থিত হয় না। এই কারণে, এই এক্সেপশনটি এই প্রক্রিয়ায় সংরক্ষণ করা সম্ভব নয়।"

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "বাগ সংক্রান্ত তথ্য বৈধ নয়"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "অনুগ্রহ করে বৈধ ব্যবহারকারীর নাম, পাসওয়ার্ড ও বাগের সংক্ষিপ্ত বিবরণে উপলব্ধ করুন।"

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "লগ-ইন করতে ব্যর্থ"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr "উল্লিখিত ব্যবহারকারীর নাম ও পাসওয়ার্ড সহযোগে %s-তে লগ-ইন করতে সমস্যা।"

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "বাগ নির্মিত হয়েছে"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"আপনার দ্বারা উপলব্ধ traceback-টি সহ একটি নতুন বাগ নির্মাণ করা হয়েছে। অনুগ্রহ করে কিছু অতিরিক্ত তথ্য যেমন, বাগ উৎপন্ন হওয়ার সময় সঞ্চালিত কর্ম, স্ক্রিন-শট ও অন্যান্য প্রয়োজনীয় সামগ্রী এই বাগের মধ্যে অন্তর্ভুক্ত করুন:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "বাগ আপডেট করা হয়েছে"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"এই তথ্য বিশিষ্ট একটি বাগ বর্তমানে উপস্থিত রয়েছে।  সংশ্লিষ্ট বাগের অনুলিপি প্রাপকদের তালিকায় আপনার অ্যাকাউন্ট যোগ করা হয়েছে ও আপনার দ্বারা উপলব্ধ traceback-টি একটি বিবৃতি রূপে সংযোজন করা হয়েছে।  অনুগ্রহ করে নিম্নলিখিত বাগের মধ্যে অতিরিক্ত তথ্য যোগ করুন:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "ডিবাগ করুন (_D)"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "প্রস্থান (_E)"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr "ব্যবস্থা না করা একটি এক্সেপশন উৎপন্ন হয়েছে।  এটি সম্ভবত একটি বাগ।  অনুগ্রহ করে, এক্সেপশনের বিবরণের একটি প্রতিলিপি সংরক্ষণ করুন ও একটি বাগ দায়ের করুন।"

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "তথ্য"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "বিবরণ (_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "বাগের বিবরণ (_d)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "উদ্দিষ্ট ফাইল (_f)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"স্থানীয় সংগ্রহস্থল\n"
"Bugzilla\n"
"দূরবর্তী সার্ভার (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "traceback-র তথ্য সংরক্ষণের জন্য অনুগ্রহ করে একটি স্থান নির্বাচন করুন।"

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "সংরক্ষণ করুন"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "একটি ফাইল নির্বাচন করুন"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "হোস্ট (host:port) (_H)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "পাসওয়ার্ড (_P)"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "ব্যবহারকারীর নাম (_U)"

