# translation of python-meh.po to Gujarati
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Sweta Kothari <swkothar@redhat.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: python-meh\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-09-09 11:39+0530\n"
"Last-Translator: Sweta Kothari <swkothar@redhat.com>\n"
"Language-Team: Gujarati\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms: nplurals=2; plural=(n!=1);\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "ડમ્પ લખાયેલ"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr "ભૂલ ફાઇલ ડિસ્કમાં સફળતાપૂર્વક લખી દેવામાં આવી છે.  પ્રક્રિયા હવે બહાર નીકળશે."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "ડમ્પ લખાયેલ નથી"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "ભૂલ અહેવાલ લખતી વખતે સમસ્યા હતી."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "નેટવર્ક ઉપલ્બધ નથી"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr "ભૂલ અહેવાલનો સંગ્રહ કરી શકાતો નથી જ્યાં સુધી સક્રિય નેટવર્ક ઉપલ્બધ નથી."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"જ્યારે બગઝીલા સાથે વિચારણા કરી રહ્યા હોય ત્યારે નીચેની ભૂલ દરમ્યાન તમારી ભૂલને જમા કરી "
"શક્યા નથી:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"તમારી ભૂલ ભૂલ ક્ષેત્રોમાં ખરાબ જાણકારી દરમ્યાન અદા કરી શક્યા નથી.  આ મોટેભાગે ભૂલ જમા "
"કરવાની પ્રક્રિયામાં ભૂલ છે:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "ભૂલ જમા કરવામાં અસમર્થ"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "ભૂલ જમા કરવાનું આધારભૂત નથી"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""
"તમારી વહેંચણીને આધારભૂત ભૂલ જમા સિસ્ટમમાં પૂરુ કરાતુ નથી, તેથી તમે આ માર્ગ માં તમારા "
"અપવાદને સંગ્રહ કરી શકાતો નથી."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "અયોગ્ય ભૂલ જાણકારી"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "મહેરબાની કરીને યોગ્ય વપરાશકર્તા નામ, પાસવર્ડ, અને ટૂંકુ ભૂલ વર્ણનને પૂરુ પાડો."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "પ્રવેશ કરવાનું અસમર્થ"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr "પૂરા પાડેલ વપરાશકર્તા અને પાસવર્ડની મદદથી %s માં પ્રવેશ કરતી વખતે ભૂલ હતી."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "ભૂલ બનાવેલ"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"નવી ભૂલ જોડાયેલ તમારી ટ્રેસબુક સાથે બનાવી દેવામાં આવી છે. મહેરબાની કરીને વધારાની જાણકારીને ઉમેરો જેવી કે "
"તમે શું કરી રહ્યા હતા ક્યારે તમે ભૂલ, સ્ક્રીનશોટો, અને ગમે તે નીચેની ભૂલ ને અનૂકુળ શોધ્યુ છે:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "ભૂલ સુધારેલ"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"તમારી જાણકારી સાથે ભૂલ પહેલેથી જ અસ્તિત્વ ધરાવે છે.  તમારુ ખાતુ CC યાદીમાં ઉમેરી દેવામાં આવ્યુ છે "
"અને તમારી ટ્રેસબુક ટિપ્પણી તરીકે ઉમેરાયેલ છે.  મહેરબાની કરીને નીચેની ભૂલમાં વધારાની વર્ણનાત્મક "
"જાણકારીને ઉમેરો:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "ડિબગ (_D)"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "બહાર નીકળો (_E)"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr ""
"ન સંભાળેલ અપવાદ ઉત્પન્ન થયુ.  આ મોટેભાગે ભૂલ છે.  મહેરબાની કરીને વિગત થયેલ અપવાદની નકલનો "
"સંગ્રહ કરો અને ભૂલ અહેવાલને જમા કરો."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "જાણકારી"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "વિગતો (_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "ભૂલ વર્ણન (_d)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "લક્ષ્ય ફાઇલ (_f)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"સ્થાનિક સંગ્રહ\n"
"બગઝીલા\n"
"દૂરસ્થ સર્વર (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "તમારી ટ્રેસબુક સંગ્રહ કરવા માટે મહેરબાની કરીને લક્ષ્ય ને પસંદ કરો."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "સંગ્રહો"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "ફાઇલને પસંદ કરો"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "યજમાન (_H) (host:port)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "પાસવર્ડ (_P)"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "વપરાશકર્તા નામ (_U)"

