# translation of python-meh.master.python-meh.po to Hindi
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Rajesh Ranjan <rajesh672@gmail.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: python-meh.master.python-meh\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-09-09 13:44+0530\n"
"Last-Translator: Rajesh Ranjan <rajesh672@gmail.com>\n"
"Language-Team: Hindi <hindi.sf.net>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms: nplurals=2; plural=(n!=1);\n\n"
"\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "संनिक्षेप लिखा गया"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr "यह त्रुटि फाइल को डिस्क में सफलतापूर्वक लिखा गया. प्रोग्राम बाहर निकल जाएगा."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "संनिक्षेप नहीं लिखा गया"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "त्रुटि रिपोर्ट लिखने में एक समस्या थी."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "कोई संजाल उपलब्ध नहीं"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr "किसी बग रिपोर्ट को सहेज नहीं सकता है क्योंकि कोई सक्रिय संजाल युक्ति उपलब्ध नहीं है."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"आपका बग निम्नलिखित त्रुटि के कारण नहीं फाइल किया जा सका आपके बगजिला से संचार करने के "
"दौरान:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"आपका बग फ़ाइल नहीं किया जा सका बग संबंधित सूचना में खराब सूचना के कारण.  यह बग फ़ाइलिंग प्रोग्राम में एक त्रुटि के कारण है:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "बग फाइल करने में असमर्थ"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "बग फाइलिंग समर्थित नहीं"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""
"आपका वितरण बग फाइलिंग सिस्टम का समर्थन नहीं देता है इसलिए आप इस तरह से अपवाद सहेज "
"नहीं सकते हैं."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "अमान्य बग जानकारी"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "एक वैध उपयोक्तानाम, कूटशब्द, और संक्षिप्त बग विवरण दें."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "लॉगिन में असमर्थ"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr "%s में लॉगिंग करने में त्रुटि थी दिए गए उपयोक्तानाम व कूटशब्द के प्रयोग से."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "बग निर्मित"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"आपके ट्रैसबैक के साथ एक नया बनाया गया है. कृपया अतिरिक्त सूचना जोड़ें ताकि आप क्या कर रहे "
"थे जब आप बग सामने आया, स्क्रीनशॉट, अथवा जो कुछ भी बग के लिए उचित हो:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "बग अद्यतनीकृत"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"आपकी सूचना के साथ बग पहले से मौजूद है.  आपके खाते को CC सूची में जोड़ दिया गया है और आपका "
"ट्रैसबैक एक टिप्पणी के रूप में जोड़ा गया था.  कृपया निम्नलिखित विवरणात्मक सूचना बग में "
"दाखिल करें:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "डिबग करें (_D)"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "निकास (_E)"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr "कोई अनियंत्रित अपवाद आई.  यह अधिक संभव एक बग के कारण है.  कृपया विस्तृत अपवाद की नक़ल सहेजें और बग रिपोर्ट फ़ाइल करें."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "सूचना"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "विवरण (_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "बग विवरण (_d)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "गंतव्य फाइल (_f)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"स्थानीय भंडारण\n"
"बगजिला\n"
"दूरस्थ सर्वर (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "अपने ट्रैसबैक को सहेजने के लिए अपना गंतव्य चुनें."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "सहेजें"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "एक फाइल चुनें"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "_Host (host:port)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "शब्दकूट (_P)"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "उपयोक्ता नाम (_U)"

