# Swedish translation of python-meh.
# Copyright © 2009-2010 Free Software Foundation, Inc.
# This file is distributed under the same license as the python-meh package.
# Magnus Larsson <fedoratrans@gmail.com>, 2009.
# Göran Uddeborg <goeran@uddeborg.se>, 2010.
#
# $Id: python-meh.po,v 1.2 2010-03-18 23:29:10+01 göran Exp $
#
msgid ""
msgstr ""
"Project-Id-Version: python-meh\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2010-03-18 23:28+0100\n"
"Last-Translator: Göran Uddeborg <goeran@uddeborg.se>\n"
"Language-Team: Swedish <tp-sv@listor.tp-sv.se>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "Dump skriven"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr "Felrapporten har sparats på disk. Programmet kommer nu avslutas."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "Dump ej skriven"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "Det uppstod ett problem vid skrivandet av felrapporten."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "Inget nätverk tillgängligt"

#: ../src/handler.py:220
msgid ""
"Cannot save a bug report since there is no active network device available."
msgstr ""
"Kan inte spara felrapporten eftersom det inte finns någon aktiv "
"nätverksenhet tillgänglig."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"Ditt fel kunde inte registreras på grund av följande fel vid kommunikationen med bugzilla:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"Ditt fel kunde inte registreras på gund av felaktig information i felrapportfälten.  Detta är med största sannolikhet ett fel i felrapporteringsprogrammet:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "Kan inte skicka felrapport"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "Sändning av felrapporter stöds inte"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr "Din distribution stödjer inte ett felrapporteringssystem som stöds, så du kan inte spara ditt undantag på detta sätt."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "Ogiltig felrapportinformation"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "Ange ett giltigt användarnamn, lösenord och en kort felbeskrivning."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "Kan inte logga in"

#: ../src/savers.py:63
#, python-format
msgid ""
"There was an error logging into %s using the provided username and password."
msgstr "Ett fel inträffade vid inloggningen på %s med det angivna användarnamnet och lösenordet."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "Felrapport skapad"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"En ny felrapport har skapats med din spårningsinformation bifogad.  Lägg till ytterligare information såsom vad du gjorde när du stötte på felet, skärmutskrifter, och vad mer som kan vara relevant för det följande felet:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "Felrapport uppdaterad"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"Ett fel med din information finns redan.  Ditt konto har lagts till till kopielistan och ditt stackspår lades till som en kommentar.  Lätt till ytterligare beskrivande information till följande felrapport:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "_Felsöka"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "_Avsluta"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr "Ett undantag som inte hanterades inträffade.  Detta är med största sannolikhet ett fel.  Spara en kopia av det detaljerade undantaget och skapa en felrapport."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "Info"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "_Detaljer"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "Fel_beskrivning"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "Mål_fil"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"Lokal lagring\n"
"Bugzilla\n"
"Fjärrserver (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "Välj en plats att spara ditt stackspår."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "Spara"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "Välj en fil"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "_Värd (värd:port)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "_Lösenord"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "_Användarnamn"
