# translation of python-meh.master.python-meh.po to Tamil
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# I. Felix <ifelix@redhat.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: python-meh.master.python-meh\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-08-28 11:12+0530\n"
"Last-Translator: I. Felix <ifelix@redhat.com>\n"
"Language-Team: Tamil <fedora-trans-ta@redhat.com>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms: nplurals=2; plural=(n!=1);\\n\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "டம்பால் எழுதப்பட்டது"

#: ../src/handler.py:210
msgid "The error file has been successfully written to the disk.  The program will now exit."
msgstr "பிழையான கோப்பானது வெற்றிகரமாக வட்டிக்கு எழுதியது. இப்போது அந்த நிரல் வெறியே உள்ளது."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "டம்ப்பால் எழுதப்படாத"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "அங்கே பிழை குறிப்பை எழுதுவதில் ஒரு சிக்கல்."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "பிணையம் இருக்கவில்லை"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr "செயல்பாட்டிலுள்ள சாதனம் கிடைக்கும் வரை அங்கே ஒரு பிழை குறிப்பை சேமிக்க முடியாது."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating with bugzilla:\n"
"\n"
"%s"
msgstr ""
"உங்களது பிழையானது கோப்பிடப்படவில்லை காரணம் இவை bugzillaக்கு தெரிவிக்கும் போது பிழை:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"உங்களது பிழை நிரப்பவில்லை ஏனெனில் பிழை புலங்களிலுள்ள தவனாறன தகவலால் நிரப்பபடவில்லை.  இது முக்கியமான பிழை நிரப்பும் நிரலின் பிழையாகும்:\n"
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "கோப்பு பிழையை செய்ய முடியவில்லை"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "பிழை துணைபுரியவில்லை"

#: ../src/savers.py:48
msgid "Your distribution does not provide a supported bug filing system, so you cannot save your exception this way."
msgstr "உங்களது விநியோகம் துணைபுரியப்பட்ட ஒரு பிழை நிரப்பும் கணினிக்கு தருகிறது, எனவே உங்களது விதிவிலக்கை இவ்வழியில் சேமிக்க முடியாது."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "தவறான பிழைத் தகவல்"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr "ஓரு சரியான பயனர்பெயரை,கடவுச்சொல், மற்றும் சிறிய பிழை விளக்கத்தையும் தரவும்."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "உட்புக முடியவில்லை"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr "அங்கே %sக்குள் உட்புக தரப்பட்ட பயனர்பெயர் மற்றும் கடவுச்சொல்லை உட்புகுத்துவதில் பிழை."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "பிழை உருவாக்கப்பட்டது"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add additional information such as what you were doing when you encountered the bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"ஒரு புதிய பிழை உங்களது பின் அடையாளத்துடன் உருவாக்கப்பட்டு சேர்க்கப்படுகிறது. கூடுதல் தகவலான என்ன நீங்கள் செய்கிறீர்கள் எப்போது நேராய் பிழை , ஸ்க்ரீன்ஷாட்டுகள், மற்றும் பின்வரும் பிழையில் பொருத்தமாக சேர்க்கிறது:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "பிழை மேம்படுத்தப்பட்டது"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to the CC list and your traceback added as a comment.  Please add additional descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"ஒரு பிழையுடன் உங்களது தகவல் ஏற்கனவே உள்ளது. CC பட்டியலுடன் உங்களது கணக்குகள் சேர்க்கப்பட்டது  மற்றும் உங்களது பின்அடையாளத்தை ஒரு கருத்தாக சேர்க்கப்படுகிறது. பின்வரும் விளக்கப்பட்ட கூடுதல் தகவல் பின்வரும் பிழையை சேர்க்கிறது:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "பிழை (_D)"

#: ../src/ui/gui.py:87
#: ../src/ui/gui.py:152
msgid "_Exit"
msgstr "வெளியேறு (_E)"

#: ../src/ui/gui.py:92
msgid "An unhandled exception has occurred.  This is most likely a bug.  Please save a copy of the detailed exception and file a bug report."
msgstr "ஒரு கையாளப்படாத விதிவிலக்கு ஏற்பட்டுவிட்டது. இது முக்கியமாக ஒரு பிழையாகும். ஒருவிவரமான விதிவிலக்கு மற்றும் கோப்பு பிழை குறிப்பு நகலை சேமி."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "தகவல்"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "விவரங்கள் (_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "பிழை விளக்கம் ( _d)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "இலக்கு கோப்பு ( _f)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"உள்ளமை சேமிப்பகம்\n"
"Bugzilla\n"
"தொலை சேவையகம்scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "உங்களது பின்அடையாளத்திற்கு ஒரு இலக்கை தேர்ந்தெடுத்து சேமிக்கிறது."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "சேமி"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "ஒரு கோப்பை தேர்ந்தெடு"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "புரவலன் (புரவல:துறை) (_H)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "கடவுச்சொல் (_P)"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "பயனர் பெயர் (_U)"

