# translation of python-meh.master.python-meh.po to Telugu
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Krishna Babu K <kkrothap@redhat.com>, 2009.
msgid ""
msgstr ""
"Project-Id-Version: python-meh.master.python-meh\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-07-16 15:00-0400\n"
"PO-Revision-Date: 2009-09-08 12:57+0530\n"
"Last-Translator: Krishna Babu K <kkrothap@redhat.com>\n"
"Language-Team: Telugu <en@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: KBabel 1.11.4\n"
"Plural-Forms: nplurals=2; plural=(n!=1);\n\n"

#: ../src/handler.py:209
msgid "Dump Written"
msgstr "డంపు వ్రాయబడింది"

#: ../src/handler.py:210
msgid ""
"The error file has been successfully written to the disk.  The program will "
"now exit."
msgstr ""
"దోషపు దస్త్రము సమర్ధవంతంగా డిస్కునకు వ్రాయబడింది.  ప్రోగ్రాము "
"యిప్పుడు "
"నిష్క్రమిస్తుంది."

#: ../src/handler.py:215
msgid "Dump Not Written"
msgstr "డంపు వ్రాయబడలేదు"

#: ../src/handler.py:216
msgid "There was a problem writing the error report."
msgstr "దోష నివేదికను వ్రాయుటలో అక్కడ వొక దోషమువుంది."

#: ../src/handler.py:219
msgid "No Network Available"
msgstr "నెట్వర్కు అందుబాటులో లేదు"

#: ../src/handler.py:220
msgid "Cannot save a bug report since there is no active network device available."
msgstr ""
"ఎటువంటి క్రియాశీల నెట్వర్కు పరికరము అందుబాటులో లేని కారణంగా బగ్ నివేదిక దాయుట "
"వీలుపడదు."

#: ../src/savers.py:34
#, python-format
msgid ""
"Your bug could not be filed due to the following error when communicating "
"with bugzilla:\n"
"\n"
"%s"
msgstr ""
"బగ్‌జిల్లాతో సంప్రదించునప్పుడు ఈ క్రింది దోషము కారణంగా మీ బగ్ "
"నమోదు "
"కాలేదు:\n"
"\n"
"%s"

#: ../src/savers.py:37
#, python-format
msgid ""
"Your bug could not be filed due to bad information in the bug fields.  This "
"is most likely an error in the bug filing program:\n"
"\n"
"%s"
msgstr ""
"బగ్ క్షేత్రములనందలి చెడ్డ సమాచారము కారణంగా మీ బగ్ నమోదు చేయబడలేక పోయింది.  "
"ఇది "
"సాదారణంగా బగ్ నమోదీకరణ ప్రోగ్రామునందలి దోషము కావచ్చు: "
"\n"
"%s"

#: ../src/savers.py:41
msgid "Unable To File Bug"
msgstr "బగ్ నమోదు చేయలేక పోయింది"

#: ../src/savers.py:47
msgid "Bug Filing Not Supported"
msgstr "బగ్ నమోదీకరణ మద్దతించబడుటలేదు"

#: ../src/savers.py:48
msgid ""
"Your distribution does not provide a supported bug filing system, so you "
"cannot save your exception this way."
msgstr ""
"మీకు పంపిణీ చేసినవారు బగ్ నమోదీకరణ వ్యవస్థకు మద్దతు అందిచుటలేదు, అందువలన "
"మీరు "
"మీ ఆక్షేపణలను ఈ విధంగా దాయలేరు."

#: ../src/savers.py:54
msgid "Invalid Bug Information"
msgstr "చెల్లని బగ్ సమాచారము"

#: ../src/savers.py:55
msgid "Please provide a valid username, password, and short bug description."
msgstr ""
"దయచేసి చెల్లునటువంటి వినియోగదారినామము, సంకేతపదము, మరియు పొట్టి "
"బగ్ వివరణను అందించుము."

#: ../src/savers.py:62
msgid "Unable To Login"
msgstr "లాగిన్ కాలేక పోయింది"

#: ../src/savers.py:63
#, python-format
msgid "There was an error logging into %s using the provided username and password."
msgstr ""
"అందించబడిన వినియోగదారినామము మరియు సంకేతపదము వుపయోగించి %sనకు "
"లాగిన్ అవుటలో వొక దోషమువుంది."

#. Tell the user we created a new bug for them and that they should
#. go add a descriptive comment.
#: ../src/savers.py:99
msgid "Bug Created"
msgstr "బగ్ సృష్టించబడింది"

#: ../src/savers.py:100
#, python-format
msgid ""
"A new bug has been created with your traceback attached. Please add "
"additional information such as what you were doing when you encountered the "
"bug, screenshots, and whatever else is appropriate to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"మీరు అందిచిన ట్రేస్‌బాక్ అనుభందించి కొత్త బగ్ సృష్టించబడింది. మీకు బగ్ వచ్చినప్పుడు "
"మీరు "
"యేమి చేస్తున్నారో, దానికి సంభందించిన స్క్రీనుషాట్లు వంటి అదనపు సమాచారాన్ని, మరియు "
"క్రింది బగ్‌కు "
"సంభందించిన యే యితర సమాచారాన్ని అయినా దయచేసి "
"జతపరచండి:\n"
"\n"
"%s/%s"

#. Tell the user which bug they've been CC'd on and that they should
#. go add a descriptive comment.
#: ../src/savers.py:114
msgid "Bug Updated"
msgstr "బగ్ నవీకరించబడింది"

#: ../src/savers.py:115
#, python-format
msgid ""
"A bug with your information already exists.  Your account has been added to "
"the CC list and your traceback added as a comment.  Please add additional "
"descriptive information to the following bug:\n"
"\n"
"%s/%s"
msgstr ""
"మీరు అందించిన సమాచారముతో వొక బగ్ యిప్పటికే వుంది.  మీ ఖాతా "
"CC జాబితానకు "
"జతచేయబడింది మరియు మీ ట్రేస్‌బాక్ వ్యాఖ్యానము వలె జతచేయబడింది.  క్రింది "
"బగ్‌కు సంభందించిన "
"అదనపు వివరణాత్మక సమాచారాన్ని దయచేసి జతపరచండి:\n"
"\n"
"%s/%s"

#. Set the buttons.
#: ../src/ui/gui.py:85
msgid "_Debug"
msgstr "డీబగ్ (_D)"

#: ../src/ui/gui.py:87 ../src/ui/gui.py:152
msgid "_Exit"
msgstr "నిష్క్రమించు (_E)"

#: ../src/ui/gui.py:92
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report."
msgstr ""
"ఒక సంభాలించని ఆక్షేపణ యెదురైంది.  ఇది సాధారణంగా బగ్.  "
"దయచేసి "
"విశదీకృత ఆక్షేపణ నకలును దాయండి మరియు బగ్ నివేదికను నమోదుచేయండి."

#: tmp/detailed-dialog.glade.h:1
msgid "Info"
msgstr "సమాచారము"

#: tmp/detailed-dialog.glade.h:2
msgid "_Details"
msgstr "వివరములు (_D)"

#: tmp/exnSave.glade.h:1
msgid "Bug _description"
msgstr "బగ్ వివరణ (_d)"

#: tmp/exnSave.glade.h:2
msgid "Destination _file"
msgstr "గమ్యపు దస్త్రము (_f)"

#: tmp/exnSave.glade.h:3
msgid ""
"Local storage\n"
"Bugzilla\n"
"Remote server (scp)"
msgstr ""
"స్థానిక నిల్వ\n"
"బగ్‌జిల్లా\n"
"దూరస్థ సేవిక (scp)"

#: tmp/exnSave.glade.h:6
msgid "Please choose a destination for saving your traceback."
msgstr "మీ ట్రేస్‌బాక్‌ను దాయుటకు దయచేసి గమ్యాన్ని యెంచుకొనండి."

#: tmp/exnSave.glade.h:7
msgid "Save"
msgstr "దాయుము"

#: tmp/exnSave.glade.h:8
msgid "Select A File"
msgstr "దస్త్రమును యెంపికచేయుము"

#: tmp/exnSave.glade.h:9
msgid "_Host (host:port)"
msgstr "హోస్టు (host:port) (_H)"

#: tmp/exnSave.glade.h:10
msgid "_Password"
msgstr "సంకేతపదము (_P)"

#: tmp/exnSave.glade.h:11
msgid "_User name"
msgstr "వినియోగదారి నామము (_U)"

